[bastion]
81.26.185.39

[services_in]
10.2.0.22

[services_out]
10.2.0.19
    
[webservers]
10.2.0.18
10.2.1.31

[grafana]
81.26.189.95
[prometheus]

[all_services:children]
services_in
services_out
webservers

[all_services:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -o StrictHostKeyChecking=no -W %h:%p -q -i ~/.ssh/yc_key  agz@81.26.185.39"'
