[bastion]
51.250.46.38

[services_in]
10.2.0.7

[services_out]
10.2.0.5
    
[webservers]
10.2.0.26
10.2.1.18

[grafana]
81.26.188.27
[prometheus]

[all_services:children]
services_in
services_out
webservers

[all_services:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -o StrictHostKeyChecking=no -W %h:%p -q -i ~/.ssh/yc_key  agz@51.250.46.38"'
