[bastion]
81.26.176.63

[services_in]
10.2.0.4

[services_out]
10.2.0.5
    
[webservers]
10.2.0.8
10.2.1.8

[grafana]
81.26.188.216
[prometheus]
84.201.148.224
[all_services:children]
services_in
services_out
webservers

[all_services:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -o StrictHostKeyChecking=no -W %h:%p -q -i ~/.ssh/yc_key  agz@81.26.176.63"'
